name: context-examples

on: ['push']

jobs:
  my-context:
    runs-on: ubuntulatest
    env:
      MY_ACTION: ${{ github.action }}
    steps:
      - name: "My Step"
        run: echo "Hello! {github.action}"