name: context-examples

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My Step"
        run: echo "Hello! $ACTION by $ACTOR"
        env:
          ACTION: ${{ github.action }}
          ACTOR: ${{ github.actor }}
